build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs, Testing the refreshing of the config at run time! "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
